[package]
name = "machineemu"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "machineemu"

[dependencies]
base64 = "0.22"
axum.workspace = true
hyper.workspace = true
hyper-util.workspace = true
clap.workspace = true
futures-util.workspace = true
machineemu-core = { workspace = true, features = ["api-schema"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
time = { version = "0.3.47", features = ["formatting"] }

[dev-dependencies]
tower.workspace = true

[lints]
workspace = true
